server:
  port: 8090

spring:
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true 
  application:
    name: restaurant-server
               
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    
eureka:  
   client:    
     serviceUrl:
      defaultZone: http://localhost:8761/eureka
      register-with-eureka: true