server:
  port: 8090

spring:
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true        
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true